##
##    Project: SDDC.Lab
##    Authors: Luis Chanu & Rutger Blom
##   Filename: utils/util_ShowPythonVersion.yml
##
---
- hosts: localhost
  vars_files:
    - ../software.yml
    - ../config.yml
  tasks:
    - ansible.builtin.debug: var=ansible_python_interpreter
    - ansible.builtin.debug: var=ansible_python_version
